apiVersion: v1
kind: Service
metadata:
  name: test-devops
  labels:
    run: cerebro
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: test-devops